export const GET_CHALLENGES = 'GET_CHALLENGES';
export const DELETE_CHALLENGES = 'DELETE_CHALLENGES';
export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';

export const GET_REQUESTS = 'GET_REQUESTS';
export const DELETE_REQUESTS = 'DELETE_REQUESTS';
